# envoy-routes/argocd-routes.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-server
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "argocd.kube"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argocd-server
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-metrics
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "metrics.argocd.kube"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /server
      backendRefs:
        - name: argocd-server-metrics
          port: 8083
    - matches:
        - path:
            type: PathPrefix
            value: /repo
      backendRefs:
        - name: argocd-repo-server
          port: 8084
    - matches:
        - path:
            type: PathPrefix
            value: /appset
      backendRefs:
        - name: argocd-applicationset-controller
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /notifications
      backendRefs:
        - name: argocd-notifications-controller-metrics
          port: 9001
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argocd-metrics
          port: 8082